//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using LIbraryDemo.Client.Interfaces;
using LIbraryDemo.Client.Models;

namespace LibraryDemo.Client.Models;

public class Author : Document
{
    public string Name { get; set; }
    public string Nationality { get; set; }
    public System.DateTimeOffset DateOfBirth { get; set; }
}

public partial class Book : Document
{
    public string BookId { get; set; }
    public System.DateTimeOffset CreationDate { get; set; }
    public string Title { get; set; }
    public string AuthorId { get; set; }
    public string Publisher { get; set; }
    public int PublicationYear { get; set; }
    public string Genre { get; set; }
    public double Price { get; set; }
    public int QuantityAvailable { get; set; }

}

public partial class CreateAuthor : ICreateDocument
{
    public string Name { get; set; }
    public string Nationality { get; set; }
    public System.DateTimeOffset DateOfBirth { get; set; }
}

public partial class CreateBook : ICreateDocument
{
    public string Title { get; set; }
    public string AuthorId { get; set; }
    public string Publisher { get; set; }
    public int PublicationYear { get; set; }
    public string Genre { get; set; }
    public double Price { get; set; }
    public int QuantityAvailable { get; set; }
}

public partial class Login
{
    public string Email { get; set; }
    public string Password { get; set; }
}

public partial class Register : ICreateDocument
{
    public string Email { get; set; }
    public string Password { get; set; }
    public string DisplayName { get; set; }
}

public partial class User
{
    public string Email { get; set; }
    public string DisplayName { get; set; }
    public string Token { get; set; }

}